[phases.setup]
nixPkgs = ["nodejs_23"]

[variables]
NIXPACKS_NODE_VERSION = "23"

[phases.install]
cmds = ["rm -rf node_modules package-lock.json && npm install --include=dev"]

[phases.build]
cmds = ["npm run build"]
